const APP_KEY='hambank_demo_v4';
const now=()=>Date.now();
const fmt=n=>new Intl.NumberFormat('fa-IR').format(Math.round(n));
const state=JSON.parse(localStorage.getItem(APP_KEY)||'null')||{
  onboard:0, registered:false, loggedIn:false, phone:'', quizDone:false, quizScore:49, quizLabel:'M — ریسک‌پذیری متوسط', amount:100000000,
  legal:false, unlocked:false, execution:'pending', executedAt:null, reminderAt:null, tab:'home', goals:[], incomeFixed:45000000, incomeVariable:12000000,
  loans:[{name:'وام خودرو',installment:8500000,total:24,paid:7,rate:23}], theme:'light', font:'normal', notifications:true, sms:true
};
const save=()=>localStorage.setItem(APP_KEY,JSON.stringify(state));
const $=s=>document.querySelector(s);
const app=document.getElementById('app');
const portfolioBase=state.amount||100000000;
function shell(content,{tabs=false,top=true}={}){
  app.innerHTML=`<div class="app-shell"><div class="phone">${top?topbar():''}${content}${tabs?tabbar():''}</div></div>`;
}
function topbar(){return `<div class="topbar"><div class="brand"><span class="mark"></span>همبانک</div><div class="actions"><button class="pill-btn" onclick="toast('ارتقای اشتراک در نسخه دمو')">👑 ارتقای اشتراک</button><button class="icon-btn" onclick="openInbox()">✉️<span class="dot"></span></button><button class="icon-btn" onclick="openAlerts()">🔔${state.execution==='pending'?'<span class="dot"></span>':''}</button></div></div>`}
function tabbar(){const tabs=[['home','⌂','خانه'],['invest','▥','دستیار سرمایه‌گذاری'],['finance','▣','دستیار مالی'],['more','⊞','سایر']];return `<div class="tabs">${tabs.map(t=>`<button class="tab ${state.tab===t[0]?'active':''}" onclick="goTab('${t[0]}')"><span class="ico">${t[1]}</span>${t[2]}</button>`).join('')}</div>`}
function toast(msg){let d=document.createElement('div');d.textContent=msg;Object.assign(d.style,{position:'absolute',bottom:'92px',right:'18px',left:'18px',background:'#0d2442',color:'#fff',padding:'12px',borderRadius:'14px',zIndex:99,textAlign:'center'});$('.phone').appendChild(d);setTimeout(()=>d.remove(),1800)}
function boot(){ if(state.registered&&!state.loggedIn) return login(); if(state.loggedIn) return main(); return onboarding(); }
function onboarding(){
 const slides=[
  ['دستیار مالی و سرمایه‌گذاری شما','همبانک کمک می‌کند تصمیم‌های مالی را منظم‌تر، شخصی‌تر و آگاهانه‌تر بگیرید.'],
  ['اول شما را می‌شناسیم','با ساخت شخصیت مالی، افق زمانی و ترجیحات شما را می‌فهمیم تا پیشنهادها متناسب‌تر باشند.'],
  ['پیشنهاد، متناسب با شما','پیشنهاد سرمایه‌گذاری بر اساس اطلاعات شما ساخته می‌شود؛ همبانک اجرای مستقیم خرید و فروش را انجام نمی‌دهد.'],
  ['کنار شما می‌مانیم','پس از اجرا، عملکرد پرتفوی را پایش می‌کنیم و برای تصمیم‌های بعدی همراهتان می‌مانیم.']
 ]; const i=state.onboard||0; shell(`<div class="screen"><div class="brand"><span class="mark"></span>همبانک</div><div class="hero"><h1>${slides[i][0]}</h1><p>${slides[i][1]}</p></div><div class="onboard-art"><div class="orb o1"></div><div class="orb o2"></div><div class="chartline"><svg viewBox="0 0 300 90" fill="none"><path d="M5 72 C45 64 55 44 88 49 S130 68 160 38 S210 48 248 21 S280 20 296 10" stroke="#1677c8" stroke-width="5" stroke-linecap="round"/></svg></div></div><div class="dots">${slides.map((_,j)=>`<i class="${j===i?'on':''}"></i>`).join('')}</div>${i<3?`<button class="cta" onclick="nextSlide()">ادامه</button>`:`<button class="cta" onclick="startQuiz()">دستیار من را بساز</button>`}<p class="center hint">برای مشاهده اسلایدها می‌توانید از دکمه ادامه استفاده کنید.</p></div>`,{top:false});
}
function nextSlide(){state.onboard=Math.min(3,(state.onboard||0)+1);save();onboarding()}
function startQuiz(){shell(`<div class="quiz-wrap"><iframe id="riskFrame" src="risk-questionnaire.html"></iframe><button id="quizContinue" class="cta quiz-continue" onclick="finishQuiz()">ادامه مسیر همبانک</button></div>`,{top:false});const f=$('#riskFrame');f.onload=()=>{setInterval(()=>{try{const w=f.contentWindow;if(w&&w.document.querySelector('.result')){state.quizScore=w.total? w.total():state.quizScore;const b=w.document.querySelector('.badge');if(b)state.quizLabel=b.textContent.trim();save();$('#quizContinue').style.display='block'}}catch(e){}},700)}}
function finishQuiz(){state.quizDone=true;save();amountStep()}
function amountStep(){shell(`<div class="screen"><div class="hero"><h1>برای اولین پیشنهاد، چه مبلغی را در نظر دارید؟</h1><p>فقط مبلغی را وارد کنید که می‌خواهید نسخه اولیه بر اساس آن ساخته شود. اطلاعات مالی کامل را بعداً و به‌تدریج اضافه می‌کنیم.</p></div><div class="amounts">${[50000000,100000000,500000000].map(v=>`<button class="${state.amount===v?'active':''}" onclick="pickAmount(${v})">${fmt(v/1000000)} میلیون</button>`).join('')}</div><div class="field"><label>مبلغ دیگر (تومان)</label><input id="customAmount" type="number" inputmode="numeric" placeholder="مثلاً 250000000"></div><button class="cta" onclick="confirmAmount()">ساخت پیشنهاد اولیه</button></div>`)}
function pickAmount(v){state.amount=v;save();amountStep()}
function confirmAmount(){const v=Number($('#customAmount')?.value||0);if(v>0)state.amount=v;save();legalStep()}
function legalStep(){shell(`<div class="screen"><div class="hero"><h1>بیانیه مسئولیت و استفاده از همبانک</h1><p>پیش از مشاهده پیشنهاد سرمایه‌گذاری، این متن را مطالعه و تأیید کنید.</p></div><div class="legal"><b>ماهیت خدمت:</b> همبانک ابزار تحلیل، سازمان‌دهی اطلاعات مالی و ارائه پیشنهادهای شخصی‌سازی‌شده است و در این نسخه اجرای مستقیم خرید و فروش یا نگهداری وجوه کاربر را انجام نمی‌دهد.<br><br><b>عدم تضمین بازده:</b> بازده گذشته یا سناریوهای نمایش‌داده‌شده تضمینی برای نتایج آینده نیستند و ارزش دارایی‌ها می‌تواند افزایش یا کاهش یابد.<br><br><b>مسئولیت تصمیم نهایی:</b> تصمیم نهایی درباره سرمایه‌گذاری و اجرای هر پیشنهاد بر عهده کاربر است. کاربر باید شرایط ابزار مالی، نقدشوندگی، کارمزدها، مالیات و ریسک‌های مرتبط را پیش از اقدام بررسی کند.<br><br><b>صحت اطلاعات:</b> کیفیت پیشنهادها به صحت اطلاعاتی وابسته است که کاربر در اختیار همبانک قرار می‌دهد. تغییر در اهداف، درآمد، بدهی یا شرایط مالی می‌تواند موجب تغییر پیشنهادها شود.<br><br><b>نسخه دمو:</b> اطلاعات عددی، قیمت‌ها و بازده‌های نمایش‌داده‌شده در این پروتوتایپ نمونه و فرضی هستند.</div><label class="check"><input id="legalCheck" type="checkbox"> متن فوق را مطالعه کرده‌ام و با شرایط استفاده موافقم.</label><button class="cta" onclick="acceptLegal()">تأیید و ادامه</button></div>`)}
function acceptLegal(){if(!$('#legalCheck').checked)return toast('برای ادامه، تأیید متن لازم است.');state.legal=true;save();previewRecommendation()}
function allocation(){return [{name:'طلا — صندوق کهربا',pct:35,color:'#e4ad31'},{name:'صندوق درآمد ثابت — کارا',pct:35,color:'#1677c8'},{name:'سهام و صندوق سهامی',pct:30,color:'#13a56e'}]}
function previewRecommendation(){const a=allocation();shell(`<div class="screen"><span class="demo-tag">نسخه دمو / اعداد فرضی</span><div class="hero"><h1>پیشنهاد اولیه شما آماده است</h1><p>ساختار کلی نسخه را می‌بینید. برای مشاهده جزئیات کامل، تحلیل و مبلغ دقیق هر بخش، نسخه را باز کنید.</p></div><div class="card"><h3>تخصیص پیشنهادی</h3><div class="alloc">${a.map(x=>`<div class="alloc-row"><div><div class="row"><b>${x.name}</b><span>${x.pct}٪</span></div><div class="bar"><span style="width:${x.pct}%;background:${x.color}"></span></div></div><b>${fmt(state.amount*x.pct/100/1000000)}م</b></div>`).join('')}</div></div><div class="card preview-lock"><div class="blurred"><h3>جزئیات نسخه</h3><p class="muted">نمادهای منتخب، دلیل تخصیص، سناریوی اجرا، تاریخ اعتبار و نکات پایش اینجا نمایش داده می‌شوند.</p><div class="grid2"><div class="metric">تحلیل بازار<b>متعادل</b></div><div class="metric">اعتبار نسخه<b>۷ روز</b></div></div></div><div class="lock-overlay">🔒 جزئیات پس از ثبت شماره</div></div><button class="cta" onclick="register()">نسخه کامل من را ببین</button></div>`)}
function register(){shell(`<div class="screen"><div class="hero"><h1>نسخه‌ات آماده است</h1><p>برای ذخیره شخصیت مالی، نسخه‌ها و ادامه پایش، شماره موبایل را تأیید کن.</p></div><div class="field"><label>شماره موبایل</label><input id="phone" inputmode="tel" value="${state.phone||'09123456789'}"></div><button class="cta" onclick="sendOtp(false)">ارسال کد تأیید</button><p class="center hint">کد دمو: 123456</p></div>`)}
function login(){shell(`<div class="screen"><div class="hero"><h1>خوش آمدید</h1><p>برای ورود به همبانک، شماره موبایل خود را وارد کنید. در ورودهای بعدی پرسشنامه تکرار نمی‌شود.</p></div><div class="field"><label>شماره موبایل</label><input id="phone" inputmode="tel" value="${state.phone||'09123456789'}"></div><button class="cta" onclick="sendOtp(true)">ارسال کد تأیید</button><button class="cta secondary" style="margin-top:10px" onclick="resetDemo()">شروع دموی کاربر جدید</button><p class="center hint">کد دمو: 123456</p></div>`,{top:false})}
function sendOtp(returning){state.phone=$('#phone').value.trim();save();shell(`<div class="screen"><div class="hero"><h1>کد تأیید را وارد کنید</h1><p>کد ۶ رقمی ارسال‌شده به ${state.phone} را وارد کنید.</p></div><div class="field"><label>کد یکبار مصرف</label><input id="otp" inputmode="numeric" maxlength="6" value="123456"></div><button class="cta" onclick="verifyOtp(${returning})">تأیید و ورود</button><p class="center hint">برای دمو، کد 123456 است.</p></div>`,{top:false})}
function verifyOtp(returning){if($('#otp').value.trim()!=='123456')return toast('کد دمو 123456 است.');state.registered=true;state.loggedIn=true;state.unlocked=true;save();if(returning){state.tab='home';save();main()}else fullRecommendation()}
function fullRecommendation(){const a=allocation();shell(`<div class="screen"><span class="demo-tag">نسخه دمو / اعداد فرضی</span><div class="hero"><h1>نسخه سرمایه‌گذاری شماره ۱</h1><p>نسخه کامل بر اساس شخصیت مالی و مبلغ اعلامی شما باز شد.</p></div><div class="card"><div class="row"><div><span class="muted">شماره نسخه</span><h3>HB-001</h3></div><div><span class="muted">اعتبار</span><h3>۷ روز</h3></div></div><div class="alloc">${a.map(x=>`<div class="alloc-row"><div><div class="row"><b>${x.name}</b><span>${x.pct}٪</span></div><div class="bar"><span style="width:${x.pct}%;background:${x.color}"></span></div></div><b>${fmt(state.amount*x.pct/100)} ت</b></div>`).join('')}</div></div><div class="card"><h3>جزئیات بخش سهامی</h3><p class="muted">ترکیب نمونه و غیرقابل اتکا برای سرمایه‌گذاری واقعی:</p><div class="grid2"><div class="metric">صندوق سهامی کاریس<b>۱۰٪</b></div><div class="metric">فملی<b>۸٪</b></div><div class="metric">فولاد<b>۶٪</b></div><div class="metric">شستا<b>۶٪</b></div></div></div><div class="notice warn">نام برخی ابزارها واقعی است، اما تخصیص‌ها، قیمت‌ها و بازده‌ها در این پروتوتایپ کاملاً فرضی هستند.</div><button class="cta" style="margin-top:12px" onclick="executionGuide()">راهنمای اجرای نسخه</button></div>`)}
function executionGuide(){shell(`<div class="screen"><div class="hero"><h1>راهنمای اجرای نسخه</h1><p>همبانک خرید و فروش را مستقیم انجام نمی‌دهد؛ این بخش فقط مسیر اجرای پیشنهادی را مرحله‌بندی می‌کند.</p></div><div class="timeline"><div class="event"><b>۱. مبلغ سرمایه‌گذاری را آماده کنید</b><p class="muted">مبلغ مبنا: ${fmt(state.amount)} تومان</p></div><div class="event"><b>۲. ابزارهای هر کلاس را بررسی کنید</b><p class="muted">شرایط صندوق، کارمزد، نقدشوندگی و اطلاعات بازار را پیش از اقدام ببینید.</p></div><div class="event"><b>۳. تخصیص پیشنهادی را اجرا کنید</b><p class="muted">در نسخه دمو: ۳۵٪ طلا، ۳۵٪ درآمد ثابت، ۳۰٪ بخش سهامی.</p></div><div class="event"><b>۴. اجرای نسخه را به همبانک اعلام کنید</b><p class="muted">پس از تأیید، پرتفوی برای پایش ساخته می‌شود.</p></div></div><button class="cta" onclick="pendingExecution()">فعلاً تمام؛ بعداً اجرا را اعلام می‌کنم</button></div>`)}
function pendingExecution(){state.execution='pending';state.reminderAt=now()+2*24*3600*1000;state.tab='home';save();main()}
function main(){if(state.tab==='home')home();else if(state.tab==='invest')invest();else if(state.tab==='finance')finance();else more()}
function goTab(t){state.tab=t;save();main()}
function values(){const base=state.amount||100000000;const factor=state.execution==='executed'?1.087:1.034;return {base,current:base*factor,profit:base*(factor-1),pct:(factor-1)*100}}
function riskText(){if(state.quizScore<=35)return ['محافظه‌کار','#1677c8'];if(state.quizScore<=55)return ['متعادل','#e4ad31'];return ['رشدگرا','#13a56e']}
function home(){const v=values(),r=riskText();shell(`<div class="screen"><div class="hero"><h1>${state.execution==='executed'?'پرتفوی شما در حال پایش است':'نسخه شما آماده اجراست'}</h1><p>${state.execution==='executed'?'آخرین تغییرات پرتفوی و اقدام‌های مهم را اینجا می‌بینید.':'بعد از اجرای نسخه، آن را اعلام کنید تا پایش واقعی از تاریخ اجرا شروع شود.'}</p></div><div class="card"><div class="row"><div><span class="muted">ارزش ${state.execution==='executed'?'روز':'فرضی'} پرتفوی</span><div class="big">${fmt(v.current)} <small>تومان</small></div></div><span class="demo-tag">دمو</span></div><div class="grid2" style="margin-top:10px"><div class="metric">سرمایه اولیه<b>${fmt(v.base)}</b></div><div class="metric">بازده ${state.execution==='executed'?'ثبت‌شده':'سناریویی'}<b class="positive">+${fmt(v.profit)} (${v.pct.toFixed(1)}٪)</b></div></div></div><div class="card"><div class="row"><div><h3>شخصیت مالی</h3><div class="big" style="color:${r[1]};font-size:22px">${r[0]}</div><span class="muted">امتیاز ${state.quizScore} از ۷۵</span></div><div class="gauge" style="width:150px;height:84px;margin:0"><div class="needle" style="transform:rotate(${(state.quizScore/75*160-80).toFixed(1)}deg);right:73px;height:62px"></div></div></div></div><h3 class="section-title">ترکیب پرتفوی</h3><div class="card alloc">${allocation().map(x=>`<div class="alloc-row"><div><div class="row"><b>${x.name}</b><span>${x.pct}٪</span></div><div class="bar"><span style="width:${x.pct}%;background:${x.color}"></span></div></div><b>${fmt(v.current*x.pct/100/1000000)}م</b></div>`).join('')}</div>${state.execution==='executed'?`<div class="notice">با اجرای توصیه شماره ۱ از تاریخ ${new Date(state.executedAt).toLocaleDateString('fa-IR')} تا امروز، در این دموی فرضی ${fmt(v.profit)} تومان معادل ${v.pct.toFixed(1)}٪ بازده ثبت شده است.</div>`:`<div class="notice warn">هنوز اجرای نسخه ثبت نشده است؛ بنابراین سود نمایش‌داده‌شده صرفاً سناریوی دمو است و «سود کاربر» محسوب نمی‌شود.</div><button class="cta" style="margin-top:10px" onclick="executionPrompt()">اعلام اجرای نسخه</button>`}</div>`,{tabs:true});}
function executionPrompt(){modal(`<h3>نسخه شماره ۱ را اجرا کردی؟</h3><p class="muted">این پاسخ مبنای ساخت پرتفوی و شروع پایش از تاریخ واقعی اجراست.</p><div class="grid2"><button class="cta" onclick="markExecuted()">👍 بله، اجرا کردم</button><button class="cta secondary" onclick="notExecuted()">👎 نه، هنوز</button></div>`)}
function markExecuted(){state.execution='executed';state.executedAt=now();state.reminderAt=null;save();main()}
function notExecuted(){state.execution='pending';state.reminderAt=now()+2*24*3600*1000;save();main();toast('دو روز دیگر دوباره یادآوری می‌کنیم.')}
function invest(){const v=values();shell(`<div class="screen"><div class="hero"><h1>دستیار سرمایه‌گذاری</h1><p>نسخه فعال، تاریخچه توصیه‌ها، پول جدید و نمای بازار در یک مسیر.</p></div><div class="card"><div class="row"><div><span class="demo-tag">نسخه فعال</span><h3>HB-001</h3></div><b class="${state.execution==='executed'?'positive':'gold'}">${state.execution==='executed'?'اجرا شده':'در انتظار اجرا'}</b></div><div class="grid2"><div class="metric">ارزش زمان توصیه<b>${fmt(v.base)}</b></div><div class="metric">ارزش روز دمو<b>${fmt(v.current)}</b></div><div class="metric">بازده نسخه<b class="positive">+${v.pct.toFixed(1)}٪</b></div><div class="metric">انقضا<b>۷ روز پس از صدور</b></div></div><h4 style="margin-top:14px">کلاس‌های دارایی</h4>${allocation().map(x=>`<div class="row" style="padding:8px 0;border-bottom:1px solid var(--line)"><span>${x.name}</span><b>${x.pct}٪</b></div>`).join('')}</div><button class="cta" onclick="newMoney()">+ پول جدید برای سرمایه‌گذاری</button><h3 class="section-title">تاریخچه توصیه‌ها</h3><div class="timeline"><div class="event"><b>HB-001 — نسخه فعلی</b><p class="muted">صادرشده امروز • ${state.execution==='executed'?'اجرا شده':'در انتظار اجرا'}</p></div><div class="event"><b>نسخه قبلی دمو</b><p class="muted">نمونه تاریخچه برای نمایش ساختار؛ ۲.۴٪ بازده فرضی</p></div></div><h3 class="section-title">نمای بازار</h3>${marketCards()}</div>`,{tabs:true})}
function marketCards(){const m=[['🥇','طلا','3,845,000','+1.2%'],['📈','شاخص کل بورس','2,246,341','+0.8%'],['₮','تتر','59,870','-0.3%']];return `<div class="stack">${m.map(x=>`<div class="card market-card"><div class="coin">${x[0]}</div><div><b>${x[1]}</b><div class="muted">داده فرضی برای دمو</div></div><div><b>${x[2]}</b><div class="${x[3][0]==='+'?'positive':'negative'}">${x[3]}</div></div></div>`).join('')}</div>`}
function newMoney(){modal(`<h3>سرمایه‌گذاری با مبلغ جدید</h3><p class="muted">همبانک مبلغ جدید را با شخصیت مالی، اهداف، بدهی‌ها و نسخه فعال ترکیب می‌کند و در صورت نیاز نسخه جدید می‌سازد.</p><div class="field"><label>مبلغ جدید (تومان)</label><input id="newMoneyValue" type="number" value="50000000"></div><button class="cta" onclick="recalcRecommendation()">دریافت توصیه جدید</button>`)}
function recalcRecommendation(){const m=Number($('#newMoneyValue').value||0);if(m<=0)return;state.amount+=m;save();closeModal();toast('نسخه جدید دمو با مبلغ تازه محاسبه شد.');invest()}
const goalCats={
'اهداف مسکن و املاک':['خرید خانه اول','خرید خانه بزرگ‌تر','خرید ملک سرمایه‌گذاری','خرید مطب / دفتر کار','ساخت یا بازسازی ملک'],
'اهداف بازنشستگی':['ایجاد سرمایه بازنشستگی','حفظ سطح زندگی بعد از بازنشستگی','ایجاد درآمد ماهانه پس از توقف کار'],
'اهداف خانواده و فرزندان':['هزینه تحصیل فرزند','خرید خانه برای فرزند','ازدواج فرزند','حمایت مالی از خانواده'],
'اهداف سبک زندگی':['خرید خودرو','تعویض خودرو','سفرهای بزرگ','خرید کالاهای ارزشمند','ارتقای سبک زندگی'],
'اهداف سرمایه‌گذاری و ثروت‌سازی':['افزایش ثروت','رسیدن به عدد مشخص دارایی','ایجاد درآمد غیرفعال','استقلال مالی'],
'اهداف کسب‌وکار و حرفه‌ای':['راه‌اندازی کسب‌وکار','توسعه کسب‌وکار','سرمایه آموزش و ارتقای حرفه‌ای'],
'اهداف سلامت و مراقبت':['ذخیره هزینه‌های درمانی آینده','بیمه تکمیلی / ذخیره سلامت','مراقبت بلندمدت در سالمندی'],
'اهداف خیرخواهانه و انتقال ثروت':['کمک به خیریه','ایجاد صندوق خانوادگی','انتقال ثروت به نسل بعد','ارث']};
function finance(){const debt=state.loans.reduce((s,l)=>s+l.installment*(l.total-l.paid),0);shell(`<div class="screen"><div class="hero"><h1>دستیار مالی</h1><p>اهداف، درآمد و بدهی‌ها را به‌تدریج تکمیل کنید تا پیشنهادهای سرمایه‌گذاری دقیق‌تر شوند.</p></div><div class="grid2"><div class="metric">درآمد ثابت ماهانه<b>${fmt(state.incomeFixed)}</b></div><div class="metric">درآمد غیرثابت<b>${fmt(state.incomeVariable)}</b></div><div class="metric">بدهی باقیمانده<b>${fmt(debt)}</b></div><div class="metric">اهداف فعال<b>${state.goals.length||0}</b></div></div><h3 class="section-title">پیشرفت اهداف</h3><div class="card">${state.goals.length?state.goals.map(g=>`<div class="goal"><div class="row"><b>${g.name}</b><span>${g.years} سال</span></div><div class="progress"><span style="width:${g.progress}%"></span></div><div class="muted">اولویت ${g.priority} • ${g.progress}٪ پیشرفت دمو</div></div>`).join(''):`<p class="muted">هنوز هدفی ثبت نکرده‌اید. با تعریف اولین هدف، همبانک می‌تواند تصمیم‌های سرمایه‌گذاری را با افق واقعی شما هماهنگ کند.</p><button class="cta" onclick="goalFlow()">تعریف اولین هدف</button>`}</div>${state.goals.length?`<button class="cta ghost" style="margin-top:10px" onclick="goalFlow()">+ هدف جدید</button>`:''}<h3 class="section-title">ورود اطلاعات مالی</h3><div class="card"><div class="field"><label>درآمد ثابت ماهانه</label><input id="incomeFixed" type="number" value="${state.incomeFixed}"></div><div class="field"><label>درآمد ماهانه غیرثابت (میانگین)</label><input id="incomeVar" type="number" value="${state.incomeVariable}"></div><button class="cta secondary" onclick="saveIncome()">ذخیره اطلاعات درآمد</button></div><h3 class="section-title">بدهی‌ها و اقساط</h3><div class="card">${state.loans.map(l=>`<div class="goal"><b>${l.name}</b><div class="muted">قسط ${fmt(l.installment)} تومان • ${l.paid} از ${l.total} پرداخت شده • سود ${l.rate}٪</div><div class="progress"><span style="width:${l.paid/l.total*100}%"></span></div></div>`).join('')}<button class="cta ghost" style="margin-top:10px" onclick="loanFlow()">+ افزودن بدهی / وام</button></div></div>`,{tabs:true})}
function saveIncome(){state.incomeFixed=Number($('#incomeFixed').value||0);state.incomeVariable=Number($('#incomeVar').value||0);save();toast('اطلاعات مالی ذخیره شد.')}
function goalFlow(){modal(`<h3>هدف مالی جدید</h3><div class="accordion">${Object.entries(goalCats).map(([k,v],i)=>`<details ${i===0?'open':''}><summary>${k}</summary>${v.map(x=>`<label class="check"><input type="radio" name="goalName" value="${x}"> ${x}</label>`).join('')}</details>`).join('')}</div><div class="grid2"><div class="field"><label>اولویت</label><select id="goalPriority"><option>1</option><option>2</option><option>3</option></select></div><div class="field"><label>افق زمانی</label><select id="goalYears"><option value="1">۱ سال</option><option value="3">۳ سال</option><option value="5" selected>۵ سال</option><option value="10">۱۰ سال</option></select></div></div><button class="cta" onclick="saveGoal()">ثبت هدف</button>`)}
function saveGoal(){const x=document.querySelector('input[name=goalName]:checked');if(!x)return toast('یک هدف را انتخاب کنید.');state.goals.push({name:x.value,priority:Number($('#goalPriority').value),years:Number($('#goalYears').value),progress:Math.floor(18+Math.random()*45)});save();closeModal();finance()}
function loanFlow(){modal(`<h3>افزودن وام یا بدهی ثابت</h3><div class="field"><label>عنوان</label><input id="loanName" value="وام مسکن"></div><div class="field"><label>مبلغ هر قسط</label><input id="loanInst" type="number" value="12000000"></div><div class="grid2"><div class="field"><label>تعداد کل اقساط</label><input id="loanTotal" type="number" value="36"></div><div class="field"><label>اقساط پرداخت‌شده</label><input id="loanPaid" type="number" value="6"></div></div><div class="field"><label>نرخ سود وام (%)</label><input id="loanRate" type="number" value="23"></div><button class="cta" onclick="saveLoan()">ثبت بدهی</button>`)}
function saveLoan(){state.loans.push({name:$('#loanName').value,installment:Number($('#loanInst').value),total:Number($('#loanTotal').value),paid:Number($('#loanPaid').value),rate:Number($('#loanRate').value)});save();closeModal();finance()}
function more(){shell(`<div class="screen"><div class="hero"><h1>سایر</h1><p>تنظیمات، حساب کاربری، اشتراک، درباره همبانک و ارتباط با ما.</p></div><div class="stack"><div class="card"><h3>تنظیمات اپلیکیشن</h3><div class="field"><label>اندازه فونت</label><select onchange="state.font=this.value;save()"><option value="normal">عادی</option><option value="large">بزرگ</option></select></div><label class="check"><input type="checkbox" ${state.notifications?'checked':''} onchange="state.notifications=this.checked;save()"> دریافت اعلان‌ها</label><label class="check"><input type="checkbox" ${state.sms?'checked':''} onchange="state.sms=this.checked;save()"> دریافت پیامک‌های ضروری</label><button class="cta secondary" onclick="toast('تم تاریک در نسخه بعدی پروتوتایپ')">🌙 تنظیم تم و نایت مود</button></div><div class="card"><h3>حساب کاربری</h3><p class="muted">شماره: ${state.phone||'—'}</p><div class="row"><span>اشتراک فعلی</span><b>دمو</b></div><div class="row" style="margin-top:10px"><span>آخرین تراکنش اشتراک</span><b>۰ تومان</b></div></div><div class="card"><h3>درباره همبانک</h3><p class="muted">همبانک دستیار مالی و سرمایه‌گذاری برای شناخت بهتر وضعیت مالی، دریافت پیشنهاد، راهنمای اجرا و پایش پس از سرمایه‌گذاری است.</p><h4>مشاوران نمونه دمو</h4><div class="advisor"><div class="avatar">م</div><div><b>نام مشاور مالی — نمونه</b><div class="muted">رزومه و مجوزها در نسخه اصلی از داده تاییدشده بارگذاری می‌شود.</div></div></div><div class="advisor" style="margin-top:10px"><div class="avatar">ا</div><div><b>نام مشاور اقتصادی — نمونه</b><div class="muted">اطلاعات این بخش در پروتوتایپ عمداً فرضی است.</div></div></div></div><div class="card"><h3>انتقادات و پیشنهادات</h3><div class="field"><textarea rows="3" placeholder="نظر شما..."></textarea></div><button class="cta secondary" onclick="toast('بازخورد دمو ثبت شد.')">ارسال بازخورد</button></div><button class="cta ghost logout" onclick="logout()">خروج از حساب کاربری</button></div></div>`,{tabs:true})}
function openInbox(){modal(`<h3>صندوق پیام همبانک</h3><div class="stack"><div class="card"><b>نسخه سرمایه‌گذاری HB-001</b><p class="muted">نسخه شخصی‌سازی‌شده شما آماده مشاهده است.</p></div><div class="card"><b>گزارش پرتفوی</b><p class="muted">نمونه گزارش دمو برای نمایش ساختار Inbox.</p></div></div>`)}
function openAlerts(){modal(`<h3>اعلان‌ها و اقدام‌های لازم</h3>${state.execution==='pending'?`<div class="card"><b>نسخه شماره ۱ را اجرا کردی؟</b><p class="muted">برای شروع پایش واقعی، وضعیت اجرا را مشخص کن.</p><div class="grid2"><button class="cta" onclick="markExecuted()">👍 بله، اجرا کردم</button><button class="cta secondary" onclick="notExecuted()">👎 نه، هنوز</button></div></div>`:`<div class="notice">فعلاً اقدام ضروری ندارید. پایش پرتفوی ادامه دارد.</div>`}<div class="card" style="margin-top:10px"><b>یادآوری دوره‌ای</b><p class="muted">در محصول واقعی، اگر نسخه در وضعیت «در انتظار اجرا» بماند، حدود ۴۸ ساعت بعد این اعلان فعال می‌شود.</p></div>`)}
function modal(html){const b=document.createElement('div');b.className='modal-backdrop';b.id='modal';b.innerHTML=`<div class="modal"><div class="row"><h3 style="margin:0">همبانک</h3><button class="icon-btn" onclick="closeModal()">×</button></div>${html}</div>`;$('.phone').appendChild(b)}
function closeModal(){document.getElementById('modal')?.remove()}
function logout(){state.loggedIn=false;save();boot()}
function resetDemo(){localStorage.removeItem(APP_KEY);location.reload()}
boot();
