const APP_KEY='hambank_demo_v5';
const now=()=>Date.now();
const fmt=n=>new Intl.NumberFormat('fa-IR').format(Math.round(Number(n)||0));
const faDate=t=>new Date(t).toLocaleDateString('fa-IR');
const MARKET={
  updated:'۱۷ شهریور ۱۴۰۵',
  source:'TGJU',
  gold18Toman:23489300,
  goldChange:1.85,
  tedpix:7074945,
  tedpixChange:2.42,
  tetherToman:226589,
  tetherChange:null
};
const STOCK_PRICES={فملی:13500,فولاد:9800,شستا:1450}; // قیمت نمونه برای پروتوتایپ؛ بازار واقعی در صفحه نمای بازار جداست
const defaultState={
  onboard:0,registered:false,loggedIn:false,phone:'',quizDone:false,quizScore:49,quizLabel:'M — ریسک‌پذیری متوسط',amount:100000000,
  legal:false,unlocked:false,execution:'pending',executedAt:null,executionReason:null,reminderAt:null,tab:'home',goals:[],incomeFixed:45000000,incomeVariable:12000000,
  loans:[{name:'وام خودرو',installment:8500000,total:24,paid:7,rate:23}],theme:'light',font:'normal',notifications:true,sms:true,
  recommendations:[{id:'HB-001',issuedAt:now(),expiresAt:now()+7*24*3600*1000,amount:100000000,horizon:5,status:'active',allocation:[35,35,30]}],
  declaredAssets:[]
};
const stored=JSON.parse(localStorage.getItem(APP_KEY)||'null')||{};
const state=Object.assign({},defaultState,stored);
if(!Array.isArray(state.recommendations)||!state.recommendations.length) state.recommendations=defaultState.recommendations;
if(!Array.isArray(state.declaredAssets)) state.declaredAssets=[];
const save=()=>localStorage.setItem(APP_KEY,JSON.stringify(state));
const $=s=>document.querySelector(s);
const app=document.getElementById('app');
function shell(content,{tabs=false,top=true,back=null}={}){
  app.innerHTML=`<div class="app-shell"><div class="phone">${top?topbar(back):''}${content}${tabs?tabbar():''}</div></div>`;
  applyPrefs();
}
function topbar(back){return `<div class="topbar"><div class="brand">${back?`<button class="icon-btn" onclick="${back}">←</button>`:''}<span class="mark"></span>همبانک</div><div class="actions"><button class="pill-btn" onclick="toast('ارتقای اشتراک در نسخه دمو')">👑 ارتقای اشتراک</button><button class="icon-btn" onclick="openInbox()">✉️<span class="dot"></span></button><button class="icon-btn" onclick="openAlerts()">🔔${state.execution==='pending'?'<span class="dot"></span>':''}</button></div></div>`}
function tabbar(){const tabs=[['home','⌂','خانه'],['invest','▥','دستیار سرمایه‌گذاری'],['finance','▣','دستیار مالی'],['more','⊞','سایر']];return `<div class="tabs">${tabs.map(t=>`<button class="tab ${state.tab===t[0]?'active':''}" onclick="goTab('${t[0]}')"><span class="ico">${t[1]}</span>${t[2]}</button>`).join('')}</div>`}
function toast(msg){let d=document.createElement('div');d.textContent=msg;Object.assign(d.style,{position:'absolute',bottom:'92px',right:'18px',left:'18px',background:'#0d2442',color:'#fff',padding:'12px',borderRadius:'14px',zIndex:99,textAlign:'center'});$('.phone').appendChild(d);setTimeout(()=>d.remove(),1800)}
function applyPrefs(){document.documentElement.dataset.font=state.font||'normal';document.documentElement.dataset.theme=state.theme||'light'}
function boot(){if(state.registered&&!state.loggedIn)return login();if(state.loggedIn)return main();return onboarding()}
function onboarding(){
 const slides=['assets/onboarding-1.png','assets/onboarding-2.png','assets/onboarding-3.png','assets/onboarding-4.png'];const i=Math.max(0,Math.min(3,state.onboard||0));
 shell(`<div class="onboarding-stage"><div id="onboardingFrame" class="onboarding-frame"><img src="${slides[i]}" alt="اسلاید معرفی همبانک ${i+1}">${i>0?`<button class="onboarding-hotspot prev" onclick="prevSlide()"></button>`:''}${i<3?`<button class="onboarding-hotspot next" onclick="nextSlide()"></button>`:`<button class="onboarding-hotspot start" onclick="startQuiz()"></button>`}</div></div>`,{top:false});setupOnboardingGestures();
}
function setupOnboardingGestures(){const el=$('#onboardingFrame');if(!el)return;let x0=null,y0=null;el.addEventListener('touchstart',e=>{const t=e.changedTouches[0];x0=t.clientX;y0=t.clientY},{passive:true});el.addEventListener('touchend',e=>{if(x0===null)return;const t=e.changedTouches[0],dx=t.clientX-x0,dy=t.clientY-y0;x0=y0=null;if(Math.abs(dx)<45||Math.abs(dx)<Math.abs(dy))return;dx<0?nextSlide():prevSlide()},{passive:true})}
function nextSlide(){state.onboard=Math.min(3,(state.onboard||0)+1);save();onboarding()}function prevSlide(){state.onboard=Math.max(0,(state.onboard||0)-1);save();onboarding()}
function startQuiz(){shell(`<div class="quiz-wrap"><iframe id="riskFrame" src="risk-questionnaire.html"></iframe><button id="quizContinue" class="cta quiz-continue" onclick="finishQuiz()">ادامه مسیر همبانک</button></div>`,{top:false});const f=$('#riskFrame');f.onload=()=>{setInterval(()=>{try{const w=f.contentWindow;if(w&&w.document.querySelector('.result')){state.quizScore=w.total?w.total():state.quizScore;const b=w.document.querySelector('.badge');if(b)state.quizLabel=b.textContent.trim();save();$('#quizContinue').style.display='block'}}catch(e){}},700)}}
function finishQuiz(){state.quizDone=true;save();amountStep()}
function amountStep(){shell(`<div class="screen"><div class="hero"><h1>برای اولین پیشنهاد، چه مبلغی را در نظر دارید؟</h1><p>فقط مبلغی را وارد کنید که می‌خواهید نسخه اولیه بر اساس آن ساخته شود.</p></div><div class="amounts">${[50000000,100000000,500000000].map(v=>`<button class="${state.amount===v?'active':''}" onclick="pickAmount(${v})">${fmt(v/1000000)} میلیون</button>`).join('')}</div><div class="field"><label>مبلغ دیگر (تومان)</label><input id="customAmount" type="number" inputmode="numeric"></div><button class="cta" onclick="confirmAmount()">ساخت پیشنهاد اولیه</button></div>`,{top:false})}
function pickAmount(v){state.amount=v;save();amountStep()}function confirmAmount(){const v=Number($('#customAmount')?.value||0);if(v>0)state.amount=v;state.recommendations[0].amount=state.amount;save();legalStep()}
function legalStep(){shell(`<div class="screen"><div class="hero"><h1>بیانیه مسئولیت و استفاده از همبانک</h1><p>پیش از مشاهده پیشنهاد سرمایه‌گذاری، این متن را مطالعه و تأیید کنید.</p></div><div class="legal"><b>ماهیت خدمت:</b> همبانک ابزار تحلیل، سازمان‌دهی اطلاعات مالی و ارائه پیشنهادهای شخصی‌سازی‌شده است و اجرای مستقیم خرید و فروش یا نگهداری وجوه کاربر را انجام نمی‌دهد.<br><br><b>عدم تضمین بازده:</b> بازده گذشته یا سناریوهای نمایش‌داده‌شده تضمینی برای نتایج آینده نیستند.<br><br><b>مسئولیت تصمیم نهایی:</b> تصمیم نهایی درباره سرمایه‌گذاری و اجرای هر پیشنهاد بر عهده کاربر است.<br><br><b>صحت اطلاعات:</b> کیفیت پیشنهادها به صحت اطلاعاتی وابسته است که کاربر ارائه می‌دهد.<br><br><b>نسخه دمو:</b> اعداد توصیه و بازده در این پروتوتایپ نمونه هستند.</div><label class="check"><input id="legalCheck" type="checkbox"> متن فوق را مطالعه کرده‌ام و موافقم.</label><button class="cta" onclick="acceptLegal()">تأیید و ادامه</button></div>`,{top:false})}
function acceptLegal(){if(!$('#legalCheck').checked)return toast('برای ادامه، تأیید متن لازم است.');state.legal=true;save();previewRecommendation()}
function allocation(){return [{name:'طلا — صندوق کهربا',pct:35,color:'#e4ad31'},{name:'صندوق درآمد ثابت — کارا',pct:35,color:'#1677c8'},{name:'سهام و صندوق سهامی',pct:30,color:'#13a56e'}]}
function previewRecommendation(){const a=allocation();shell(`<div class="screen"><span class="demo-tag">نسخه دمو / اعداد توصیه فرضی</span><div class="hero"><h1>پیشنهاد اولیه شما آماده است</h1><p>ساختار کلی نسخه را می‌بینید. برای مشاهده جزئیات کامل، نسخه را باز کنید.</p></div><div class="card"><h3>تخصیص پیشنهادی</h3><div class="alloc">${a.map(x=>`<div class="alloc-row"><div><div class="row"><b>${x.name}</b><span>${x.pct}٪</span></div><div class="bar"><span style="width:${x.pct}%;background:${x.color}"></span></div></div><b>${fmt(state.amount*x.pct/100/1000000)}م</b></div>`).join('')}</div></div><div class="card preview-lock"><div class="blurred"><h3>جزئیات نسخه</h3><p class="muted">نمادها، دلیل تخصیص، سناریوی اجرا و تاریخ اعتبار.</p></div><div class="lock-overlay">🔒 جزئیات پس از ثبت شماره</div></div><button class="cta" onclick="register()">نسخه کامل من را ببین</button></div>`,{top:false})}
function register(){shell(`<div class="screen"><div class="hero"><h1>نسخه‌ات آماده است</h1><p>برای ذخیره شخصیت مالی و مشاهده نسخه کامل، شماره موبایل را تأیید کن.</p></div><div class="field"><label>شماره موبایل</label><input id="phone" inputmode="tel" value="${state.phone||'09123456789'}"></div><button class="cta" onclick="sendOtp(false)">ارسال کد تأیید</button><p class="center hint">کد دمو: 123456</p></div>`,{top:false})}
function login(){shell(`<div class="screen"><div class="hero"><h1>خوش آمدید</h1><p>برای ورود، شماره موبایل خود را وارد کنید.</p></div><div class="field"><label>شماره موبایل</label><input id="phone" inputmode="tel" value="${state.phone||'09123456789'}"></div><button class="cta" onclick="sendOtp(true)">ارسال کد تأیید</button><button class="cta secondary" style="margin-top:10px" onclick="resetDemo()">شروع دموی کاربر جدید</button><p class="center hint">کد دمو: 123456</p></div>`,{top:false})}
function sendOtp(returning){state.phone=$('#phone').value.trim();save();shell(`<div class="screen"><div class="hero"><h1>کد تأیید را وارد کنید</h1><p>کد ارسال‌شده به ${state.phone}</p></div><div class="field"><input id="otp" inputmode="numeric" maxlength="6" value="123456"></div><button class="cta" onclick="verifyOtp(${returning})">تأیید و ورود</button></div>`,{top:false})}
function verifyOtp(returning){if($('#otp').value.trim()!=='123456')return toast('کد دمو 123456 است.');state.registered=true;state.loggedIn=true;state.unlocked=true;save();returning?enterPersonalProfile():fullRecommendation()}
function fullRecommendation(){const a=allocation();shell(`<div class="screen"><span class="demo-tag">نسخه دمو / اعداد توصیه فرضی</span><div class="hero"><h1>نسخه سرمایه‌گذاری شماره ۱</h1><p>نسخه کامل بر اساس شخصیت مالی و مبلغ اعلامی شما.</p></div><div class="card"><div class="row"><div><span class="muted">شماره نسخه</span><h3>HB-001</h3></div><div><span class="muted">اعتبار</span><h3>۷ روز</h3></div></div><div class="alloc">${a.map(x=>`<div class="alloc-row"><div><div class="row"><b>${x.name}</b><span>${x.pct}٪</span></div><div class="bar"><span style="width:${x.pct}%;background:${x.color}"></span></div></div><b>${fmt(state.amount*x.pct/100)} ت</b></div>`).join('')}</div></div><div class="card"><h3>جزئیات بخش سهامی</h3><div class="grid2"><div class="metric">صندوق سهامی کاریس<b>۱۰٪</b></div><div class="metric">فملی<b>۸٪</b></div><div class="metric">فولاد<b>۶٪</b></div><div class="metric">شستا<b>۶٪</b></div></div></div><div class="recommend-actions"><button class="cta" onclick="executionGuide()">راهنمای اجرای نسخه</button><button class="cta profile-entry" onclick="enterPersonalProfile()">ورود به پروفایل شخصی</button></div></div>`,{top:false})}
function enterPersonalProfile(){state.tab='home';save();main()}
function executionGuide(){shell(`<div class="screen"><div class="hero"><h1>راهنمای اجرای نسخه</h1><p>همبانک خرید و فروش را مستقیم انجام نمی‌دهد؛ مسیر اجرای پیشنهادی را مرحله‌بندی می‌کند.</p></div><div class="timeline"><div class="event"><b>۱. مبلغ را آماده کنید</b></div><div class="event"><b>۲. ابزارهای هر کلاس را بررسی کنید</b></div><div class="event"><b>۳. تخصیص را اجرا کنید</b><p class="muted">۳۵٪ طلا، ۳۵٪ درآمد ثابت، ۳۰٪ سهامی</p></div><div class="event"><b>۴. اجرای نسخه را اعلام کنید</b></div></div><button class="cta" onclick="pendingExecution()">بعداً اجرا را اعلام می‌کنم</button></div>`,{top:false})}
function pendingExecution(){state.execution='pending';state.reminderAt=now()+2*24*3600*1000;state.tab='home';save();main()}
function main(){if(state.tab==='home')home();else if(state.tab==='invest')invest();else if(state.tab==='finance')finance();else more()}
function goTab(t){state.tab=t;save();main()}
function values(){const base=state.amount||100000000;const factor=state.execution==='executed'?1.087:1.034;return{base,current:base*factor,profit:base*(factor-1),pct:(factor-1)*100}}
function riskText(){if(state.quizScore<=35)return['محافظه‌کار','#1677c8'];if(state.quizScore<=55)return['متعادل','#e4ad31'];return['رشدگرا','#13a56e']}
function declaredAssetValue(a){if(a.type==='gold')return Number(a.qty||0)*MARKET.gold18Toman;if(a.type==='stock')return Number(a.qty||0)*(STOCK_PRICES[a.symbol]||0);if(a.type==='property')return Number(a.value||0);if(a.type==='fixed')return Number(a.value||0);return 0}
function declaredTotal(){return state.declaredAssets.reduce((s,a)=>s+declaredAssetValue(a),0)}
function declaredPortfolioCard(){if(!state.declaredAssets.length)return `<div class="card"><p class="muted">هنوز دارایی قبلی ثبت نشده است. از تب دستیار مالی → «وارد کردن اطلاعات مالی» دارایی‌ها را اضافه کنید.</p></div>`;return `<div class="card"><div class="row"><h3>دارایی‌های اعلام‌شده شما</h3><b>${fmt(declaredTotal())} تومان</b></div>${state.declaredAssets.map(a=>`<div class="row asset-line"><span>${assetTitle(a)}</span><b>${fmt(declaredAssetValue(a))}</b></div>`).join('')}<div class="muted">این پرتفوی از پرتفوی نسخه‌های اجراشده همبانک جدا نگهداری می‌شود.</div></div>`}
function assetTitle(a){return a.type==='gold'?`طلا — ${a.qty} گرم`:a.type==='stock'?`سهام ${a.symbol} — ${fmt(a.qty)} سهم`:a.type==='property'?`ملک — ارزش تقریبی اعلامی`:a.type==='fixed'?`صندوق درآمد ثابت`:a.type}
function home(){const v=values(),r=riskText();shell(`<div class="screen"><div class="hero"><h1>${state.execution==='executed'?'پرتفوی همبانک در حال پایش است':'نسخه شما آماده اجراست'}</h1><p>${state.execution==='executed'?'ارزش و عملکرد نسخه اجراشده را جدا از دارایی‌های قبلی شما پایش می‌کنیم.':'پس از اجرا، تاریخ واقعی را ثبت کنید تا پایش از همان روز شروع شود.'}</p></div><div class="card"><div class="row"><div><span class="muted">ارزش ${state.execution==='executed'?'روز':'سناریویی'} پرتفوی همبانک</span><div class="big">${fmt(v.current)} <small>تومان</small></div></div><span class="demo-tag">دمو</span></div><div class="grid2"><div class="metric">سرمایه اولیه<b>${fmt(v.base)}</b></div><div class="metric">بازده<b class="positive">+${fmt(v.profit)} (${v.pct.toFixed(1)}٪)</b></div></div></div><div class="card"><div class="row"><div><h3>شخصیت مالی</h3><div class="big" style="color:${r[1]};font-size:22px">${r[0]}</div><span class="muted">امتیاز ${state.quizScore} از ۷۵</span></div><div class="gauge" style="width:150px;height:84px;margin:0"><div class="needle" style="transform:rotate(${(state.quizScore/75*160-80).toFixed(1)}deg);right:73px;height:62px"></div></div></div></div><h3 class="section-title">پرتفوی نسخه‌های اجراشده همبانک</h3><div class="card alloc">${allocation().map(x=>`<div class="alloc-row"><div><div class="row"><b>${x.name}</b><span>${x.pct}٪</span></div><div class="bar"><span style="width:${x.pct}%;background:${x.color}"></span></div></div><b>${fmt(v.current*x.pct/100/1000000)}م</b></div>`).join('')}</div>${state.execution==='executed'?`<div class="notice">از تاریخ اجرای ثبت‌شده ${faDate(state.executedAt)} تا امروز، بازده دمو ${fmt(v.profit)} تومان است.</div>`:`<div class="notice warn">اجرای نسخه هنوز ثبت نشده است؛ این بازده صرفاً سناریوی دمو است.</div>`}<h3 class="section-title">پرتفوی دارایی‌های اعلام‌شده</h3>${declaredPortfolioCard()}</div>`,{tabs:true})}
function executionPrompt(){modal(`<h3>نسخه شماره ۱ را اجرا کردی؟</h3><p class="muted">پاسخ شما مبنای پایش بعدی است.</p><div class="grid2"><button class="cta" onclick="askExecutionDate()">بله، اجرا کردم</button><button class="cta secondary" onclick="askNonExecutionReason()">نه، اجرا نکردم</button></div>`)}
function askExecutionDate(){modalReplace(`<h3>تاریخ اجرا را ثبت کن</h3><p class="muted">ارزش روز و بازده از همین تاریخ محاسبه می‌شود.</p><div class="field"><label>تاریخ اجرا</label><input id="execDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><button class="cta" onclick="confirmExecuted()">ثبت تاریخ اجرا</button>`)}
function confirmExecuted(){const d=$('#execDate').value;if(!d)return toast('تاریخ اجرا را وارد کنید.');state.execution='executed';state.executedAt=new Date(d+'T12:00:00').getTime();state.executionReason=null;state.reminderAt=null;state.recommendations[0].status='executed';save();closeModal();main()}
function askNonExecutionReason(){modalReplace(`<h3>چرا نسخه را اجرا نکردی؟</h3><p class="muted">این پاسخ کمک می‌کند پیگیری بعدی مرتبط‌تر باشد.</p>${[['نیاز به زمان بیشتر برای تصمیم‌گیری','followup'],['در حال حاضر نقدینگی کافی ندارم','liquidity'],['برای اجرای پیشنهاد به راهنمایی بیشتری نیاز دارم','support'],['سایر','other']].map(([t,v])=>`<label class="check reason-option"><input type="radio" name="reason" value="${v}"> ${t}</label>`).join('')}<div id="otherReasonWrap" class="field"><label>توضیح اختیاری</label><textarea id="otherReason" rows="2"></textarea></div><button class="cta" onclick="saveNonExecutionReason()">ثبت و ادامه پایش</button>`)}
function saveNonExecutionReason(){const x=document.querySelector('input[name=reason]:checked');if(!x)return toast('یک دلیل را انتخاب کنید.');state.execution='pending';state.executionReason={code:x.value,text:x.parentElement.textContent.trim(),detail:$('#otherReason')?.value||'',at:now()};state.reminderAt=now()+2*24*3600*1000;save();closeModal();main();toast(x.value==='support'?'راهنمای اجرا را در پیگیری بعدی برجسته می‌کنیم.':x.value==='liquidity'?'پس از ورود پول جدید دوباره پیشنهاد می‌دهیم.':'پیگیری بعدی تنظیم شد.')}
function invest(){const v=values();shell(`<div class="screen"><div class="hero"><h1>دستیار سرمایه‌گذاری</h1><p>نسخه فعال و اقدام‌های بعدی شما.</p></div><div class="card"><div class="row"><div><span class="demo-tag">نسخه فعال</span><h3>${state.recommendations[state.recommendations.length-1].id}</h3></div><b class="${state.execution==='executed'?'positive':'gold'}">${state.execution==='executed'?'اجرا شده':'در انتظار اجرا'}</b></div><div class="grid2"><div class="metric">ارزش زمان توصیه<b>${fmt(v.base)}</b></div><div class="metric">ارزش روز دمو<b>${fmt(v.current)}</b></div><div class="metric">بازده نسخه<b class="positive">+${v.pct.toFixed(1)}٪</b></div><div class="metric">انقضا<b>۷ روز</b></div></div></div><button class="cta" onclick="newMoney()">+ پول جدید برای سرمایه‌گذاری</button><div class="menu-card" onclick="recommendationHistory()"><div><b>تاریخچه توصیه‌ها</b><div class="muted">رکورد نسخه‌ها، صدور، انقضا و بازده</div></div><span>←</span></div><div class="menu-card" onclick="marketView()"><div><b>نمای بازار</b><div class="muted">طلا، شاخص کل و تتر با آخرین داده واقعی بازیابی‌شده</div></div><span>←</span></div></div>`,{tabs:true})}
function newMoney(){modal(`<h3>سرمایه‌گذاری با مبلغ جدید</h3><p class="muted">مبلغ و افق زمانی را مشخص کنید. همبانک شرایط فعلی، اهداف و بدهی‌ها را دوباره بررسی می‌کند.</p><div class="field"><label>مبلغ جدید (تومان)</label><input id="newMoneyValue" type="number" value="50000000"></div><div class="field"><label>افق زمانی این مبلغ</label><select id="newMoneyHorizon"><option value="1">کمتر از ۳ سال</option><option value="5" selected>۳ تا ۱۰ سال</option><option value="12">بیشتر از ۱۰ سال</option></select></div><button class="cta" onclick="recalcRecommendation()">دریافت توصیه جدید</button>`)}
function recalcRecommendation(){const m=Number($('#newMoneyValue').value||0),h=Number($('#newMoneyHorizon').value||5);if(m<=0)return toast('مبلغ را وارد کنید.');const sameAllocation=true;const id=`HB-${String(state.recommendations.length+1).padStart(3,'0')}`;state.recommendations.push({id,issuedAt:now(),expiresAt:now()+7*24*3600*1000,amount:m,horizon:h,status:'active',allocation:[35,35,30],sameAsPrevious:sameAllocation});state.amount+=m;save();modalReplace(`<h3>توصیه جدید صادر شد</h3><div class="notice">با توجه به شخصیت مالی، اهداف و بدهی‌های فعلی، ساختار تخصیص همان نسخه قبلی باقی ماند. مبلغ جدید به همان سبد افزوده شد.</div><div class="card" style="margin-top:10px"><div class="row"><b>${id}</b><span>${fmt(m)} تومان</span></div>${allocation().map(x=>`<div class="row asset-line"><span>${x.name}</span><b>${x.pct}٪ — ${fmt(m*x.pct/100)}</b></div>`).join('')}</div><button class="cta" onclick="closeModal();invest()">مشاهده نسخه فعال</button>`)}
function recommendationHistory(){shell(`<div class="screen"><div class="hero"><h1>تاریخچه توصیه‌ها</h1><p>هر نسخه به‌صورت مستقل نگهداری می‌شود و تغییرات بعدی نسخه قبلی را بازنویسی نمی‌کند.</p></div><div class="timeline">${[...state.recommendations].reverse().map((r,i)=>{const days=Math.max(1,Math.floor((now()-r.issuedAt)/86400000));const p=(2.1+Math.min(days,20)*.17+i*.4).toFixed(1);return `<div class="event"><div class="card"><div class="row"><b>${r.id}</b><span class="demo-tag">${r.status==='executed'?'اجرا شده':'نسخه ثبت‌شده'}</span></div><div class="grid2"><div class="metric">تاریخ صدور<b>${faDate(r.issuedAt)}</b></div><div class="metric">تاریخ انقضا<b>${faDate(r.expiresAt)}</b></div><div class="metric">مبلغ مبنا<b>${fmt(r.amount)}</b></div><div class="metric">بازده تا امروز<b class="positive">+${p}٪</b></div></div><div class="muted">بازده در این پروتوتایپ دمو است؛ تاریخ‌ها و رکورد نسخه واقعیِ همین session هستند.</div></div></div>`}).join('')}</div></div>`,{back:'invest()'})}
function marketView(){shell(`<div class="screen"><div class="hero"><h1>نمای بازار</h1><p>آخرین داده واقعی بازیابی‌شده از اینترنت برای دموی GitHub Pages.</p></div>${marketCards()}<div class="notice">منبع: ${MARKET.source} • آخرین بازیابی: ${MARKET.updated}. برای نسخه Production اتصال Server/API و Refresh لحظه‌ای لازم است.</div></div>`,{back:'invest()'})}
function marketCards(){const m=[['🥇','طلای ۱۸ عیار',`${fmt(MARKET.gold18Toman)} تومان / گرم`,`+${MARKET.goldChange}%`],['📈','شاخص کل بورس',fmt(MARKET.tedpix),`+${MARKET.tedpixChange}%`],['₮','تتر',`${fmt(MARKET.tetherToman)} تومان`,'قیمت ریالی']];return `<div class="stack">${m.map(x=>`<div class="card market-card"><div class="coin">${x[0]}</div><div><b>${x[1]}</b><div class="muted">داده واقعی بازیابی‌شده</div></div><div><b>${x[2]}</b><div class="positive">${x[3]}</div></div></div>`).join('')}</div>`}
const goalCats={'اهداف مسکن و املاک':['خرید خانه اول','خرید خانه بزرگ‌تر','خرید ملک سرمایه‌گذاری','خرید مطب / دفتر کار'],'اهداف بازنشستگی':['ایجاد سرمایه بازنشستگی','حفظ سطح زندگی بعد از بازنشستگی','ایجاد درآمد ماهانه پس از توقف کار'],'اهداف خانواده و فرزندان':['هزینه تحصیل فرزند','خرید خانه برای فرزند','ازدواج فرزند'],'اهداف سبک زندگی':['خرید خودرو','سفرهای بزرگ','ارتقای سبک زندگی'],'اهداف سرمایه‌گذاری و ثروت‌سازی':['افزایش ثروت','ایجاد درآمد غیرفعال','استقلال مالی'],'اهداف کسب‌وکار و حرفه‌ای':['راه‌اندازی کسب‌وکار','توسعه کسب‌وکار'],'اهداف سلامت و مراقبت':['ذخیره هزینه‌های درمانی آینده','مراقبت بلندمدت در سالمندی'],'اهداف خیرخواهانه و انتقال ثروت':['کمک به خیریه','انتقال ثروت به نسل بعد','ارث']};
function finance(){const debt=state.loans.reduce((s,l)=>s+l.installment*(l.total-l.paid),0);shell(`<div class="screen"><div class="hero"><h1>دستیار مالی</h1><p>اهداف و تصویر مالی شما؛ ورود جزئیات در صفحه مجزای اطلاعات مالی انجام می‌شود.</p></div><div class="grid2"><div class="metric">درآمد ماهانه<b>${fmt(state.incomeFixed+state.incomeVariable)}</b></div><div class="metric">بدهی باقیمانده<b>${fmt(debt)}</b></div><div class="metric">دارایی اعلام‌شده<b>${fmt(declaredTotal())}</b></div><div class="metric">اهداف فعال<b>${state.goals.length}</b></div></div><button class="cta" style="margin-top:12px" onclick="financialDataPage()">وارد کردن اطلاعات مالی</button><h3 class="section-title">اهداف مالی</h3><div class="card">${state.goals.length?state.goals.map(g=>`<div class="goal"><div class="row"><b>${g.name}</b><span>${g.years} سال</span></div><div class="progress"><span style="width:${g.progress}%"></span></div><div class="muted">اولویت ${g.priority} • ${g.progress}٪ پیشرفت دمو</div></div>`).join(''):`<p class="muted">هنوز هدفی ثبت نکرده‌اید.</p>`}<button class="cta ghost" onclick="goalFlow()">${state.goals.length?'+ هدف جدید':'تعریف اولین هدف'}</button></div><h3 class="section-title">پیشرفت بدهی</h3><div class="card">${state.loans.map(l=>`<div class="goal"><div class="row"><b>${l.name}</b><span>${l.paid}/${l.total} قسط</span></div><div class="progress"><span style="width:${l.paid/l.total*100}%"></span></div></div>`).join('')}</div></div>`,{tabs:true})}
function financialDataPage(){shell(`<div class="screen"><div class="hero"><h1>ورود اطلاعات مالی</h1><p>سه بخش مستقل؛ با لمس هر کلید، فرم به شکل آسانسوری رو به پایین باز می‌شود.</p></div><div class="accordion-switch"><button onclick="toggleFinancialPanel('asset')">دارایی‌ها</button><div id="assetPanel" class="slide-panel"></div><button onclick="toggleFinancialPanel('income')">درآمدها</button><div id="incomePanel" class="slide-panel"></div><button onclick="toggleFinancialPanel('debt')">بدهی‌ها</button><div id="debtPanel" class="slide-panel"></div></div></div>`,{back:'finance()'})}
function toggleFinancialPanel(kind){['asset','income','debt'].forEach(k=>{const el=$(`#${k}Panel`);if(k!==kind){el.classList.remove('open');el.innerHTML=''}});const el=$(`#${kind}Panel`);if(el.classList.contains('open')){el.classList.remove('open');el.innerHTML='';return}el.innerHTML=kind==='asset'?assetPanelHtml():kind==='income'?incomePanelHtml():debtPanelHtml();requestAnimationFrame(()=>el.classList.add('open'))}
function assetPanelHtml(){return `<div class="panel-inner"><h3>اعلام دارایی‌های موجود</h3><div class="field"><label>کلاس دارایی</label><select id="assetType" onchange="renderAssetFields()"><option value="gold">طلا</option><option value="stock">سهام</option><option value="property">ملک</option><option value="fixed">صندوق درآمد ثابت</option></select></div><div id="assetFields">${goldFields()}</div><button class="cta" onclick="saveAsset()">ثبت دارایی</button>${state.declaredAssets.length?`<div class="stack mini-list">${state.declaredAssets.map(a=>`<div class="row"><span>${assetTitle(a)}</span><b>${fmt(declaredAssetValue(a))}</b></div>`).join('')}</div>`:''}</div>`}
function renderAssetFields(){const t=$('#assetType').value;$('#assetFields').innerHTML=t==='gold'?goldFields():t==='stock'?stockFields():t==='property'?propertyFields():fixedFields()}
function goldFields(){return `<div class="field"><label>مقدار طلا (گرم)</label><input id="assetQty" type="number" value="10"></div><div class="notice">ارزش تقریبی با قیمت واقعی فعلی طلا در نمای بازار محاسبه می‌شود.</div>`}
function stockFields(){return `<div class="grid2"><div class="field"><label>نماد</label><select id="assetSymbol"><option>فملی</option><option>فولاد</option><option>شستا</option></select></div><div class="field"><label>تعداد سهم</label><input id="assetQty" type="number" value="1000"></div></div><div class="muted">در این Prototype قیمت نمادها نمونه است؛ اتصال مستقیم به Feed بورس در نسخه Production انجام می‌شود.</div>`}
function propertyFields(){return `<div class="field"><label>ارزش تقریبی ملک (تومان)</label><input id="assetValue" type="number" value="5000000000"></div>`}
function fixedFields(){return `<div class="field"><label>ارزش فعلی صندوق درآمد ثابت (تومان)</label><input id="assetValue" type="number" value="200000000"></div>`}
function saveAsset(){const type=$('#assetType').value;let a={type};if(type==='gold')a.qty=Number($('#assetQty').value||0);if(type==='stock'){a.symbol=$('#assetSymbol').value;a.qty=Number($('#assetQty').value||0)}if(type==='property'||type==='fixed')a.value=Number($('#assetValue').value||0);state.declaredAssets.push(a);save();toggleFinancialPanel('asset');toggleFinancialPanel('asset');toast('دارایی ثبت شد و در Home جداگانه نمایش داده می‌شود.')}
function incomePanelHtml(){return `<div class="panel-inner"><h3>درآمد</h3><div class="field"><label>درآمد ثابت ماهانه</label><input id="incomeFixed" type="number" value="${state.incomeFixed}"></div><div class="field"><label>میانگین درآمد غیرثابت ماهانه</label><input id="incomeVar" type="number" value="${state.incomeVariable}"></div><button class="cta" onclick="saveIncome()">ذخیره درآمد</button></div>`}
function saveIncome(){state.incomeFixed=Number($('#incomeFixed').value||0);state.incomeVariable=Number($('#incomeVar').value||0);save();toast('اطلاعات درآمد ذخیره شد.')}
function debtPanelHtml(){return `<div class="panel-inner"><h3>بدهی و وام</h3>${state.loans.map(l=>`<div class="goal"><b>${l.name}</b><div class="muted">قسط ${fmt(l.installment)} • ${l.paid} از ${l.total} پرداخت • سود ${l.rate}٪</div></div>`).join('')}<div class="field"><label>عنوان</label><input id="loanName" value="وام مسکن"></div><div class="field"><label>مبلغ قسط</label><input id="loanInst" type="number" value="12000000"></div><div class="grid2"><div class="field"><label>کل اقساط</label><input id="loanTotal" type="number" value="36"></div><div class="field"><label>پرداخت‌شده</label><input id="loanPaid" type="number" value="6"></div></div><div class="field"><label>نرخ سود (%)</label><input id="loanRate" type="number" value="23"></div><button class="cta" onclick="saveLoan()">ثبت بدهی</button></div>`}
function saveLoan(){state.loans.push({name:$('#loanName').value,installment:Number($('#loanInst').value),total:Number($('#loanTotal').value),paid:Number($('#loanPaid').value),rate:Number($('#loanRate').value)});save();toast('بدهی ثبت شد.')}
function goalFlow(){modal(`<h3>هدف مالی جدید</h3><div class="accordion">${Object.entries(goalCats).map(([k,v],i)=>`<details ${i===0?'open':''}><summary>${k}</summary>${v.map(x=>`<label class="check"><input type="radio" name="goalName" value="${x}"> ${x}</label>`).join('')}</details>`).join('')}</div><div class="grid2"><div class="field"><label>اولویت</label><select id="goalPriority"><option>1</option><option>2</option><option>3</option></select></div><div class="field"><label>افق زمانی</label><select id="goalYears"><option value="1">۱ سال</option><option value="3">۳ سال</option><option value="5" selected>۵ سال</option><option value="10">۱۰ سال</option></select></div></div><button class="cta" onclick="saveGoal()">ثبت هدف</button>`)}
function saveGoal(){const x=document.querySelector('input[name=goalName]:checked');if(!x)return toast('یک هدف را انتخاب کنید.');state.goals.push({name:x.value,priority:Number($('#goalPriority').value),years:Number($('#goalYears').value),progress:Math.floor(18+Math.random()*45)});save();closeModal();finance()}
function more(){shell(`<div class="screen"><div class="hero"><h1>سایر</h1><p>هر بخش در صفحه مستقل خودش باز می‌شود.</p></div><div class="stack"><div class="menu-card" onclick="settingsPage()"><div><b>تنظیمات برنامه</b><div class="muted">فونت، تم، اعلان‌ها و دسترسی‌ها</div></div><span>←</span></div><div class="menu-card" onclick="accountPage()"><div><b>حساب کاربری</b><div class="muted">پروفایل، اشتراک و تراکنش‌ها</div></div><span>←</span></div><div class="menu-card" onclick="aboutPage()"><div><b>درباره همبانک</b><div class="muted">معرفی محصول و رزومه افراد نمونه</div></div><span>←</span></div><div class="menu-card" onclick="feedbackPage()"><div><b>انتقادات و پیشنهادات</b><div class="muted">ارسال بازخورد به تیم محصول</div></div><span>←</span></div></div></div>`,{tabs:true})}
function settingsPage(){shell(`<div class="screen"><div class="hero"><h1>تنظیمات برنامه</h1></div><div class="card"><div class="field"><label>اندازه فونت</label><select id="fontSetting" onchange="state.font=this.value;save();applyPrefs()"><option value="normal" ${state.font==='normal'?'selected':''}>عادی</option><option value="large" ${state.font==='large'?'selected':''}>بزرگ</option></select></div><div class="field"><label>تم</label><select onchange="state.theme=this.value;save();applyPrefs()"><option value="light">روشن</option><option value="dark">تاریک</option></select></div><label class="check"><input type="checkbox" ${state.notifications?'checked':''} onchange="state.notifications=this.checked;save()"> اعلان‌ها</label><label class="check"><input type="checkbox" ${state.sms?'checked':''} onchange="state.sms=this.checked;save()"> پیامک‌های ضروری</label></div></div>`,{back:'more()'})}
function accountPage(){shell(`<div class="screen"><div class="hero"><h1>حساب کاربری</h1><p>اطلاعات هویتی و مالی اشتراک.</p></div><div class="card"><div class="row"><span>شماره موبایل</span><b>${state.phone||'—'}</b></div><div class="row asset-line"><span>وضعیت احراز</span><b class="positive">تأییدشده</b></div><div class="row asset-line"><span>اشتراک</span><b>نسخه دمو</b></div></div><h3 class="section-title">تراکنش‌های اشتراک</h3><div class="card"><div class="row"><span>فعال‌سازی نسخه دمو</span><b>۰ تومان</b></div><div class="muted">در نسخه واقعی سوابق پرداخت، فاکتور و تمدید اشتراک اینجا ثبت می‌شود.</div></div><button class="cta ghost logout" onclick="logout()">خروج از حساب کاربری</button></div>`,{back:'more()'})}
function aboutPage(){shell(`<div class="screen"><div class="hero"><h1>درباره همبانک</h1><p>دستیار مالی و سرمایه‌گذاری برای شناخت، توصیه، راهنمای اجرا و پایش دوره‌ای.</p></div><div class="notice warn">نام‌ها و رزومه‌های زیر متعلق به افراد واقعی و عمومی هستند و صرفاً برای نمایش UX این Prototype استفاده شده‌اند؛ این صفحه هیچ ادعایی درباره همکاری یا مشاوره آنان برای همبانک ندارد.</div><h3 class="section-title">چهره‌های واقعی نمونه برای نمایش ساختار اعتماد</h3>${advisorCard('حسین عبده تبریزی','دکترای امور مالی و بانکداری از مدرسه عالی بازرگانی منچستر؛ سابقه طولانی تدریس مالی در دانشگاه‌هایی از جمله صنعتی شریف، تهران و شهید بهشتی.','ح.ع')}${advisorCard('علی سعدوندی','دکترای اقتصاد از دانشگاه تربیت مدرس؛ سابقه استادیاری بانکداری و فاینانس در دانشگاه وولونگونگ و فعالیت حرفه‌ای بانکی در سیتی‌بانک دبی.','ع.س')}${advisorCard('مهدی سوری','مدرس و تحلیلگر بازار سرمایه با تمرکز بر تحلیل بنیادی، صنایع بورسی و آموزش سرمایه‌گذاری.','م.س')}<div class="muted">در نسخه واقعی این بخش فقط با مشاوران دارای قرارداد/مجوز و رزومه تأییدشده همبانک جایگزین می‌شود.</div></div>`,{back:'more()'})}
function advisorCard(name,resume,initial){return `<div class="card advisor-card"><div class="avatar">${initial}</div><div><b>${name}</b><div class="muted">${resume}</div></div></div>`}
function feedbackPage(){shell(`<div class="screen"><div class="hero"><h1>انتقادات و پیشنهادات</h1><p>بازخورد شما مستقیماً برای بهبود تجربه محصول استفاده می‌شود.</p></div><div class="card"><div class="field"><label>موضوع</label><select><option>پیشنهاد محصول</option><option>مشکل تجربه کاربری</option><option>گزارش خطا</option><option>سایر</option></select></div><div class="field"><label>متن پیام</label><textarea rows="6" placeholder="نظر شما..."></textarea></div><button class="cta" onclick="toast('بازخورد دمو ثبت شد.')">ارسال بازخورد</button></div></div>`,{back:'more()'})}
function openInbox(){modal(`<h3>صندوق پیام همبانک</h3><div class="stack"><div class="card"><b>نسخه سرمایه‌گذاری ${state.recommendations[state.recommendations.length-1].id}</b><p class="muted">نسخه شخصی‌سازی‌شده شما ثبت شده است.</p></div><div class="card"><b>گزارش پرتفوی</b><p class="muted">گزارش دوره‌ای پایش در این بخش نگهداری می‌شود.</p></div></div>`)}
function openAlerts(){modal(`<h3>اعلان‌ها و اقدام‌های لازم</h3>${state.execution==='pending'?`<div class="card"><b>نسخه را اجرا کردی؟</b><p class="muted">برای شروع پایش واقعی، وضعیت اجرا را مشخص کن.</p><div class="grid2"><button class="cta" onclick="askExecutionDate()">بله، اجرا کردم</button><button class="cta secondary" onclick="askNonExecutionReason()">نه، اجرا نکردم</button></div>${state.executionReason?`<div class="muted" style="margin-top:10px">آخرین دلیل ثبت‌شده: ${state.executionReason.text}</div>`:''}</div>`:`<div class="notice">فعلاً اقدام ضروری ندارید. پایش ادامه دارد.</div>`}<div class="card" style="margin-top:10px"><b>یادآوری دوره‌ای</b><p class="muted">اگر نسخه در انتظار اجرا بماند، تقریباً ۴۸ ساعت بعد دوباره پیگیری می‌شود.</p></div>`)}
function modal(html){const b=document.createElement('div');b.className='modal-backdrop';b.id='modal';b.innerHTML=`<div class="modal"><div class="row"><h3 style="margin:0">همبانک</h3><button class="icon-btn" onclick="closeModal()">×</button></div>${html}</div>`;$('.phone').appendChild(b)}
function modalReplace(html){const m=$('#modal .modal');if(m)m.innerHTML=`<div class="row"><h3 style="margin:0">همبانک</h3><button class="icon-btn" onclick="closeModal()">×</button></div>${html}`}
function closeModal(){document.getElementById('modal')?.remove()}function logout(){state.loggedIn=false;save();boot()}function resetDemo(){localStorage.removeItem(APP_KEY);location.reload()}
boot();
